### ISSUE TITLE
Is it possible to manually log a user in

### ISSUE THREAD

**Issue by kiwo12345** [vinkas0/firebase-auth-laravel#1]
Thanks for sharing this!

I wonder if its possible to manually log a user in to firebase? Instead of a middleware

**Comment by vinothkannans** [comment]
Yes you can do it using Firebase custom authentication method. Already an official package available for php here https://github.com/firebase/firebase-token-generator-php.

Also you may use this package along with our [vinkas/firebase-auth-laravel](https://github.com/vinkas0/firebase-auth-laravel).

**Comment by kiwo12345** [comment]
@vinothkannans Thanks alot!
